INSERT INTO USER (ADMIN, USERNAME, NAME, PASSWORD, LOCKED) VALUES (true,'admin','Admin','A+98FnMIylJGjl2jhHcUYQ==',false);
INSERT INTO USER (ADMIN, USERNAME, NAME, PASSWORD, LOCKED) VALUES (false,'user','User','A+98FnMIylJGjl2jhHcUYQ==',false);
